steps:
- name: 'blang/latex:ctanfull'
  args: ['bash', '-c', 'rm -rf /usr/local/texlive/2017/texmf-dist/metapost/metauml; ln -svf ${PWD}/src /usr/local/texlive/2017/texmf-dist/metapost/metauml; make release-tgz']

artifacts:
  objects:
    location: 'gs://metauml'
    paths: ['metauml-$TAG_NAME-$REVISION_ID.tgz']
